/*
 * MIT License
 * Copyright (c) 2017 - 2022 _VIFEXTech
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "Arduino.h"
#include "PeripheralPins.h"


const PinMap PinMap_PWM[] = {

  {PA8,    GPIOA,  TMR1,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_2, 1, 0), GPIO_PINS_SOURCE8},/*timer1 channel1*/
  {PA9,    GPIOA,  TMR1,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_2, 2, 0), GPIO_PINS_SOURCE9},/*timer1 channel2*/
  {PA10,   GPIOA,  TMR1,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_2, 3, 0), GPIO_PINS_SOURCE10},/*timer1 channel3*/
  {PA11,   GPIOA,  TMR1,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_2, 4, 0), GPIO_PINS_SOURCE11},/*timer1 channel4*/

  {PA6,    GPIOA,  TMR3,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1, 1, 0), GPIO_PINS_SOURCE6},/*timer3 channel1*/
  {PA7,    GPIOA,  TMR3,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1, 2, 0), GPIO_PINS_SOURCE7},/*timer3 channel2*/
  {PB0,    GPIOB,  TMR3,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1, 3, 0), GPIO_PINS_SOURCE0},/*timer3 channel3*/
  {PB1,    GPIOB,  TMR3,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1, 4, 0), GPIO_PINS_SOURCE1},/*timer3 channel4*/

  {PA4,    GPIOA,  TMR14,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_4, 1, 0), GPIO_PINS_SOURCE4},/*timer14 channel1*/

  {PA2,    GPIOA,  TMR15,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_0, 1, 0), GPIO_PINS_SOURCE2},/*timer15 channel1*/
  {PA3,    GPIOA,  TMR15,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_0, 2, 0), GPIO_PINS_SOURCE3},/*timer15 channel2*/

  {PB8,    GPIOB,  TMR16,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_2, 1, 0), GPIO_PINS_SOURCE8},/*timer16 channel1*/

  {PB9,    GPIOB,  TMR17,  AT_PIN_DATA_EXT(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_2, 1, 0), GPIO_PINS_SOURCE9},/*timer17 channel1*/
  {NC,     NULL,      NP,    0,   0} 

};

const PinMap PinMap_ADC[] = {

  {PA0,    GPIOA,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 0, 0), GPIO_PINS_SOURCE0},/*ADC1 channel0*/
  {PA1,    GPIOA,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 1, 0), GPIO_PINS_SOURCE1},/*ADC1 channel1*/
  {PA2,    GPIOA,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 2, 0), GPIO_PINS_SOURCE2},/*ADC1 channel2*/
  {PA3,    GPIOA,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 3, 0), GPIO_PINS_SOURCE3},/*ADC1 channel3*/
  {PA4,    GPIOA,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 4, 0), GPIO_PINS_SOURCE4},/*ADC1 channel4*/
  {PA5,    GPIOA,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 5, 0), GPIO_PINS_SOURCE5},/*ADC1 channel5*/
  {PA6,    GPIOA,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 6, 0), GPIO_PINS_SOURCE6},/*ADC1 channel6*/
  {PA7,    GPIOA,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 7, 0), GPIO_PINS_SOURCE7},/*ADC1 channel7*/
  {PB0,    GPIOB,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 8, 0), GPIO_PINS_SOURCE0},/*ADC1 channel8*/
  {PB1,    GPIOB,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 9, 0), GPIO_PINS_SOURCE1},/*ADC1 channel9*/
  {PB2,    GPIOB,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 10, 0), GPIO_PINS_SOURCE2},/*ADC1 channel10*/
  {PB12,   GPIOB,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 11, 0), GPIO_PINS_SOURCE12},/*ADC1 channel11*/
  {PB13,   GPIOB,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 12, 0), GPIO_PINS_SOURCE13},/*ADC1 channel12*/
  {PB14,   GPIOB,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 13, 0), GPIO_PINS_SOURCE14},/*ADC1 channel13*/
  {PB15,   GPIOB,  ADC1,  AT_PIN_DATA_EXT(AT_MODE_ANALOG, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_0, 14, 0), GPIO_PINS_SOURCE15},/*ADC1 channel14*/
  {NC,     NULL,      NP,    0,   0} 


};

const PinMap PinMap_SPI_SCK[] = {

  {PA5,    GPIOA,  SPI1,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_DOWN, GPIO_MUX_0), GPIO_PINS_SOURCE5},/*SPI1 SCK pin*/
  {PB13,   GPIOB,  SPI2,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_DOWN, GPIO_MUX_0), GPIO_PINS_SOURCE13},/*SPI2 SCK pin*/
  {NC,     NULL,      NP,    0,   0} ,

};

const PinMap PinMap_SPI_MISO[] = {

  {PA6,    GPIOA,  SPI1,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_0), GPIO_PINS_SOURCE6},/*SPI1 MISO pin*/
  {PB14,   GPIOB,  SPI2,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_0), GPIO_PINS_SOURCE14},/*SPI2 MISO pin*/
  {NC,     NULL,      NP,    0,   0} ,

};

const PinMap PinMap_SPI_MOSI[] = {

  {PA7,    GPIOA,  SPI1,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_0), GPIO_PINS_SOURCE7},/*SPI1 MOSI pin*/
  {PB15,   GPIOB,  SPI2,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_0), GPIO_PINS_SOURCE15},/*SPI2 MOSI pin*/
  {NC,     NULL,      NP,    0,   0} ,

};

const PinMap PinMap_SPI_CS[] = {

  {PA4,    GPIOA,  SPI1,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_DOWN, GPIO_MUX_0), GPIO_PINS_SOURCE4},/*SPI1 CS pin*/
  {PB12,   GPIOB,  SPI2,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_DOWN, GPIO_MUX_0), GPIO_PINS_SOURCE12},/*SP2 CS pin*/
  {NC,     NULL,      NP,    0,   0} ,

};

const PinMap PinMap_USART_RX[] = {

  {PA10,   GPIOA,  USART1,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1), GPIO_PINS_SOURCE10},/*USART1 RX pin*/
  {PA3,    GPIOA,  USART2,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1), GPIO_PINS_SOURCE3},/*USART2 RX pin*/
  {PB11,   GPIOB,  USART3,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_4), GPIO_PINS_SOURCE11},/*USART3 RX pin*/
  {PA1,    GPIOA,  USART4,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_4), GPIO_PINS_SOURCE1},/*USART4 RX pin*/
  {NC,     NULL,      NP,    0,   0} ,

};

const PinMap PinMap_USART_TX[] = {

  {PA9,    GPIOA,  USART1,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1), GPIO_PINS_SOURCE9},/*USART1 TX pin*/
  {PA2,    GPIOA,  USART2,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1), GPIO_PINS_SOURCE2},/*USART2 TX pin*/
  {PB10,   GPIOB,  USART3,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_4), GPIO_PINS_SOURCE10},/*USART3 TX pin*/
  {PA0,    GPIOA,  USART4,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_4), GPIO_PINS_SOURCE0},/*USART4 TX pin*/
  {NC,     NULL,      NP,    0,   0} ,

};

const PinMap PinMap_USART_CTS[] = {

  {PA11,   GPIOA,  USART1,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1), GPIO_PINS_SOURCE11},/*USART1 CTS pin*/
  {PA0,    GPIOA,  USART2,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1), GPIO_PINS_SOURCE0},/*USART2 CTS pin*/
  {PA6,    GPIOA,  USART3,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_4), GPIO_PINS_SOURCE6},/*USART3 CTS pin*/
  {NC,     NULL,      NP,    0,   0} ,

};

const PinMap PinMap_USART_RTS[] = {

  {PA12,   GPIOA,  USART1,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1), GPIO_PINS_SOURCE12},/*USART1 RTS pin*/
  {PA1,    GPIOA,  USART2,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_1), GPIO_PINS_SOURCE1},/*USART2 RTS pin*/
  {PB14,   GPIOB,  USART3,  AT_PIN_DATA(AT_MODE_AF_PP, (uint32_t)GPIO_PULL_UP, GPIO_MUX_4), GPIO_PINS_SOURCE14},/*USART3 RTS pin*/
  {NC,     NULL,      NP,    0,   0} ,

};

const PinMap PinMap_I2C_SCL[] = {
  {PA9,   GPIOA,   I2C1,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_4), GPIO_PINS_SOURCE9},/*IIC1 SCL pin*/
  {PB6,   GPIOB,   I2C1,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_1), GPIO_PINS_SOURCE6},/*IIC1 SCL pin*/
  {PB8,   GPIOB,   I2C1,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_1), GPIO_PINS_SOURCE8},/*IIC1 SCL pin*/
  {PF1,   GPIOF,   I2C1,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_1), GPIO_PINS_SOURCE1},/*IIC1 SCL pin*/
  {PA0,   GPIOA,   I2C2,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_3), GPIO_PINS_SOURCE0},/*IIC2 SCL pin*/
  {PA11,  GPIOA,   I2C2,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_5), GPIO_PINS_SOURCE11},/*IIC2 SCL pin*/
  {PB13,  GPIOB,   I2C2,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_5), GPIO_PINS_SOURCE13},/*IIC2 SCL pin*/
  {NC,     NULL,      NP,    0,   0},
};

const PinMap PinMap_I2C_SDA[] = {
  {PA10,  GPIOA,   I2C1,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_4), GPIO_PINS_SOURCE10},/*IIC1 SDA pin*/
  {PB7,   GPIOB,   I2C1,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_1), GPIO_PINS_SOURCE7},/*IIC1 SDA pin*/
  {PB9,   GPIOB,   I2C1,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_1), GPIO_PINS_SOURCE9},/*IIC1 SDA pin*/
  {PF0,   GPIOF,   I2C1,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_1), GPIO_PINS_SOURCE0},/*IIC1 SDA pin*/
  {PA1,   GPIOA,   I2C2,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_3), GPIO_PINS_SOURCE1},/*IIC2 SDA pin*/
  {PA12,  GPIOA,   I2C2,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_5), GPIO_PINS_SOURCE12},/*IIC2 SDA pin*/
  {PB14,  GPIOB,   I2C2,   AT_PIN_DATA(AT_MODE_AF_OD, (uint32_t)GPIO_PULL_NONE, GPIO_MUX_5), GPIO_PINS_SOURCE14},/*IIC2 SDA pin*/
  {NC,     NULL,      NP,    0,   0},
};

